// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhacnuzwanwxmwwznxth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoYWNudXp3YW53eG13d3pueHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjU1OTMsImV4cCI6MjA2MjAwMTU5M30.McF8Rs6GpZ0RklnK9Q8NnJcdGmGAe-6jcJjGpUubQcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);